
build:
  version: "2.0"

accounts:
  message: "Welcome to Config server impl accounts related about DEV APIs"
  contactDetails:
    name: "config - Developer"
    email: "john@configserver.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
